<?php
// Snapshot do estoque (gerado do localhost em 2026-07-27 23:46).
// Fonte para estoque_importar.php substituir os dados na produção. NÃO editar à mão.
return array (
  'itens' => 
  array (
    0 => 
    array (
      'nome' => 'ABACAXI EM CALDA',
      'fornecedor' => 'ATACADÃO',
      'preco' => '13.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '4.000',
      'estoque_ideal' => '6.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    1 => 
    array (
      'nome' => 'AÇUCAR COLOMBO 1kg',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '3.68',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    2 => 
    array (
      'nome' => 'AÇUCAR DA BARRA 5 Kg',
      'fornecedor' => 'ATACADÃO',
      'preco' => '19.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    3 => 
    array (
      'nome' => 'ADESIVO 5X5',
      'fornecedor' => 'MIMO CRIATTIVO',
      'preco' => '0.20',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '100.000',
      'estoque_ideal' => '300.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    4 => 
    array (
      'nome' => 'ÁGUA SANITÁRIA QBOA 5l',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '14.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    5 => 
    array (
      'nome' => 'ALCOOL 46% 1l',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '6.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    6 => 
    array (
      'nome' => 'ÀLCOOL DE CEREAIS',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    7 => 
    array (
      'nome' => 'AMEIXA 1 Kg - DA CASAS',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '62.43',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    8 => 
    array (
      'nome' => 'AMENDOIM (MOÍDO FARINHA) 1.001kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '14.85',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '6.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.001',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    9 => 
    array (
      'nome' => 'AMENDOIM AMENDOÍSSIMO (MOÍDO FARINHA) 1 Kg',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '24.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    10 => 
    array (
      'nome' => 'AMIDO DE MILHO DA CASA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '3.39',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    11 => 
    array (
      'nome' => 'BANDEJA DE OVOS',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '23.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '0',
      'ativo' => '1',
    ),
    12 => 
    array (
      'nome' => 'BANDEJA LAMINADA N6',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '35.29',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    13 => 
    array (
      'nome' => 'BAUNILHA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '50.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    14 => 
    array (
      'nome' => 'BICARBONATO DE SÓDIO',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '12.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    15 => 
    array (
      'nome' => 'BLOSSONS AO LEITE 100g',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '21.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '100.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    16 => 
    array (
      'nome' => 'BLOSSONS BRANCO 100g',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '19.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '100.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    17 => 
    array (
      'nome' => 'BLOSSONS MISTO 100 g',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '34.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '100.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    18 => 
    array (
      'nome' => 'BOBINA IMPRESSORA TERMICA',
      'fornecedor' => 'MERCADÃO DA EMBALAGEM',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    19 => 
    array (
      'nome' => 'BOLACHA DE MAIZENA',
      'fornecedor' => 'ATACADÃO',
      'preco' => '13.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    20 => 
    array (
      'nome' => 'CACAU EM PÓ 500 g - HARALD',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '49.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '4.000',
      'estoque_ideal' => '8.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    21 => 
    array (
      'nome' => 'CAIXA BRANCA ALTA CUPCAKE Unid. 35x35x10',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '4.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    22 => 
    array (
      'nome' => 'CAIXA P/ DOCES 1/4 CENTO (20x20) 25 Unid',
      'fornecedor' => 'BR EMBALAGENS',
      'preco' => '50.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '50.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => '25.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    23 => 
    array (
      'nome' => 'CAIXA PARA BOLO 20X20X14',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '6.19',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    24 => 
    array (
      'nome' => 'CAIXA PARA BOLO 20X20X20',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '6.19',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    25 => 
    array (
      'nome' => 'CAIXA PARA BOLO 26X26X14',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '4.82',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    26 => 
    array (
      'nome' => 'CAIXA PARA BOLO 26X26X20',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '6.72',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    27 => 
    array (
      'nome' => 'CAIXA PARA BOLO 32X32X14',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '162.45',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => '25.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    28 => 
    array (
      'nome' => 'CAIXA PARA BOLO 32X32X20',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '197.55',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => '25.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    29 => 
    array (
      'nome' => 'CAIXA PARA BOLO 39X39X14',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '179.78',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => '25.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    30 => 
    array (
      'nome' => 'CAIXA PARA BOLO 39X39X20',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '212.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => '25.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    31 => 
    array (
      'nome' => 'CAIXA PARA DOCES 35X17,5X5',
      'fornecedor' => 'CITBOX EMBALAGENS',
      'preco' => '1.70',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    32 => 
    array (
      'nome' => 'CAIXA PARA DOCES 35X35X5',
      'fornecedor' => 'CITBOX EMBALAGENS',
      'preco' => '2.50',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    33 => 
    array (
      'nome' => 'CANELA EM PÓ 30g',
      'fornecedor' => 'ATACADÃO',
      'preco' => '2.99',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '30.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    34 => 
    array (
      'nome' => 'CEREJA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '0.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '0',
      'ativo' => '1',
    ),
    35 => 
    array (
      'nome' => 'CHANTILLY CHOCOLATE CESIBON 1lt',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '17.46',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    36 => 
    array (
      'nome' => 'CHANTILY AMELIA SUPREME 1lt',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '21.75',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '12.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    37 => 
    array (
      'nome' => 'CHOCO BALL BRANCO',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    38 => 
    array (
      'nome' => 'CHOCOLATE BLEND SICAO 2,05Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '137.96',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '2.050',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    39 => 
    array (
      'nome' => 'CHOCOLATE EM PÓ HARALD 1.010kg',
      'fornecedor' => 'ATACADÃO',
      'preco' => '38.89',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.010',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    40 => 
    array (
      'nome' => 'CHOCOLATE SICAO MEIO AMARGO 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '39.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    41 => 
    array (
      'nome' => 'COBERTURA BLEND SICAO 2 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '64.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '2.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    42 => 
    array (
      'nome' => 'COCO QUEIMADO 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '42.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    43 => 
    array (
      'nome' => 'COCO RALADO EM FLOCOS 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '55.04',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    44 => 
    array (
      'nome' => 'COCO RALADO MAIS COCO ADOÇADO 1 Kg',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '41.76',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    45 => 
    array (
      'nome' => 'COCO RALADO MEDIO SECO 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '47.79',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    46 => 
    array (
      'nome' => 'CONFETE CHOCOGIROS 500 g',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '16.83',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '3.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    47 => 
    array (
      'nome' => 'CORANTE DIVERSOS 60g',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '8.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '60.000',
      'imagem' => NULL,
      'controlar_estoque' => '0',
      'ativo' => '1',
    ),
    48 => 
    array (
      'nome' => 'CRAVO DA ÍNDIA 10g',
      'fornecedor' => 'ATACADÃO',
      'preco' => '1.80',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '10.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    49 => 
    array (
      'nome' => 'CREME DE LEITE CCGL 200ML',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '3.19',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '54.000',
      'estoque_ideal' => '216.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '200.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    50 => 
    array (
      'nome' => 'CREME DE LEITE LEITE BOM 1,030kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '14.08',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.030',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    51 => 
    array (
      'nome' => 'DAMASCO 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '69.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    52 => 
    array (
      'nome' => 'DESINFETANTE GIRANDO SOL 5l',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '16.50',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    53 => 
    array (
      'nome' => 'DESMOLDANTE CARLEX',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    54 => 
    array (
      'nome' => 'DETERGENTE YPÊ NEUTRO 500ml',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '2.15',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    55 => 
    array (
      'nome' => 'DISCO ESPUMA 25 Cm 10 Unid.',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '5.92',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '3.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    56 => 
    array (
      'nome' => 'DOCE DE LEITE TIROL 900g',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '900.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    57 => 
    array (
      'nome' => 'DOCE DE SORO DE LEITE CASA DO PANIF. 9,8KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '73.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '9.800',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    58 => 
    array (
      'nome' => 'DUREX MÉDIO',
      'fornecedor' => 'MERCADÃO DA EMBALAGEM',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    59 => 
    array (
      'nome' => 'EMBALAGEM G680 POTE PARA SOBREMESA 250 ML COM 5 UN GALVANOTEK',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '4.15',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '250.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    60 => 
    array (
      'nome' => 'EMBALAGEM G850 COPO BOLHA COM TAMPA 500 ML COM 10 UN GALVANOTEK',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '12.26',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    61 => 
    array (
      'nome' => 'EMBALAGEM POTE QUADRADO COM LACRE 250 ML COM 10 UN PRA FESTA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '11.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '250.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    62 => 
    array (
      'nome' => 'EMBALAGEM RETANGULAR G78',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '297.32',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    63 => 
    array (
      'nome' => 'EMUSTAB SELECTA 3 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '100.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '3.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    64 => 
    array (
      'nome' => 'ESPONJA DE AÇO BOMBRIL 60g',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '2.69',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '60.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    65 => 
    array (
      'nome' => 'ESPONJA DE LOUÇA',
      'fornecedor' => 'ATACADÃO',
      'preco' => '4.29',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '4.000',
      'estoque_ideal' => '12.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    66 => 
    array (
      'nome' => 'FERMENTO 250 g',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '9.38',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '6.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '250.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    67 => 
    array (
      'nome' => 'FOLHA PLÁSTICA 30X40',
      'fornecedor' => 'ATACADÃO',
      'preco' => '54.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '3.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    68 => 
    array (
      'nome' => 'FORMINHA PETALA 100 Unid.',
      'fornecedor' => 'CITBOX EMBALAGENS',
      'preco' => '3.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    69 => 
    array (
      'nome' => 'FORMINHA PETALA CANDY BRANCA BOMBOM 50 Unid.',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '2.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    70 => 
    array (
      'nome' => 'FORMINHA PETALA TRASP. 50 Unid.',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '7.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    71 => 
    array (
      'nome' => 'GELATINA SEM SABOR DA CASA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    72 => 
    array (
      'nome' => 'GLUCOSE DE MILHO - 5KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '60.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    73 => 
    array (
      'nome' => 'GRANULADO BRANCO CROCANTE 500 g - MAVALERIO',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '10.44',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    74 => 
    array (
      'nome' => 'GRANULADO HARALD MACIO 1kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '19.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '10.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    75 => 
    array (
      'nome' => 'LEITE CONDENSADO AUREA 5KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '75.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    76 => 
    array (
      'nome' => 'LEITE CONDENSADO MOÇA 395g',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '9.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '9.000',
      'estoque_ideal' => '18.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '395.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    77 => 
    array (
      'nome' => 'LEITE CONDENSADO SEMIDESNATADO BAG 5KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '62.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '6.000',
      'estoque_ideal' => '20.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    78 => 
    array (
      'nome' => 'LEITE EM PÓ CCGL 1kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '37.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '6.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    79 => 
    array (
      'nome' => 'LEITE EM PÓ NINHO 975G',
      'fornecedor' => 'ATACADÃO',
      'preco' => '59.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '975.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    80 => 
    array (
      'nome' => 'LEITE INTEGRAL 1 Lt',
      'fornecedor' => 'ATACADÃO',
      'preco' => '4.19',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    81 => 
    array (
      'nome' => 'LIMÃO',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '0.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    82 => 
    array (
      'nome' => 'LUVA VINIL SEM PÓ - G',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '21.15',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    83 => 
    array (
      'nome' => 'LUVA VINIL SEM PÓ - M',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '24.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    84 => 
    array (
      'nome' => 'MAGUARI - MARACUJÁ CONCENTRADO',
      'fornecedor' => 'ATACADÃO',
      'preco' => '6.39',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    85 => 
    array (
      'nome' => 'MANTEIGA SEM SAL 500g',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '20.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '4.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '500.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    86 => 
    array (
      'nome' => 'MARGARINA QUALY 1 KG',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '13.98',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    87 => 
    array (
      'nome' => 'MARMITA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '0.20',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    88 => 
    array (
      'nome' => 'MDF REDONDO 20 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '4.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    89 => 
    array (
      'nome' => 'MDF REDONDO 26 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '7.46',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    90 => 
    array (
      'nome' => 'MDF REDONDO 28 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '8.05',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    91 => 
    array (
      'nome' => 'MDF REDONDO 30 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '9.09',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    92 => 
    array (
      'nome' => 'MDF REDONDO 32 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '9.68',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '10.000',
      'estoque_ideal' => '15.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    93 => 
    array (
      'nome' => 'MDF REDONDO 35 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    94 => 
    array (
      'nome' => 'MDF REDONDO 38 Cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '12.24',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    95 => 
    array (
      'nome' => 'MDF RETANGULAR 31x40cm',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '11.15',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '5.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    96 => 
    array (
      'nome' => 'MILK FLAKES CALLEBAUT 1KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '229.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    97 => 
    array (
      'nome' => 'MORANGO',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '7.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    98 => 
    array (
      'nome' => 'NATA 300 g',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '10.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '300.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    99 => 
    array (
      'nome' => 'NESCAU 2 Kg',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '24.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '2.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    100 => 
    array (
      'nome' => 'NESQUIK 600G',
      'fornecedor' => 'ATACADÃO',
      'preco' => '22.50',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'G',
      'conteudo' => '600.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    101 => 
    array (
      'nome' => 'NOZES 1 Kg QUARTZO QUEBRADA - DA CASA',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '76.65',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    102 => 
    array (
      'nome' => 'NUTELLA 3kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '174.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '3.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    103 => 
    array (
      'nome' => 'ÓLEO DE SOJA 900 ml',
      'fornecedor' => 'ATACADÃO',
      'preco' => '7.49',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'ML',
      'conteudo' => '900.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    104 => 
    array (
      'nome' => 'OURO BRANCO 1kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '49.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    105 => 
    array (
      'nome' => 'PAPEL MANTEIGA 400 FOLHAS - LUTEPEL',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '148.50',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    106 => 
    array (
      'nome' => 'PASTILHA SANITARIA PATO COM 3',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '8.99',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    107 => 
    array (
      'nome' => 'PHYSALIS',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '16.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    108 => 
    array (
      'nome' => 'PISTACHE',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => NULL,
      'estoque_ideal' => NULL,
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    109 => 
    array (
      'nome' => 'PÓ DIVERSOS',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '11.95',
      'estoque_atual' => '0.000',
      'estoque_minimo' => NULL,
      'estoque_ideal' => NULL,
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    110 => 
    array (
      'nome' => 'PRATO ESPUMA 25 Cm 10 Unid.',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '14.66',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '3.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    111 => 
    array (
      'nome' => 'ROLO DE PERFEX',
      'fornecedor' => 'ATACADÃO',
      'preco' => '70.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    112 => 
    array (
      'nome' => 'SACO DE LIXO 50LT REFORÇADO',
      'fornecedor' => 'ATACADÃO',
      'preco' => '27.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'L',
      'conteudo' => '50.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    113 => 
    array (
      'nome' => 'SACO P/ CONFEITAR M - MAGO 50 UNID.',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '40.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    114 => 
    array (
      'nome' => 'SACO VIRGEM',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    115 => 
    array (
      'nome' => 'SONHO DE VALSA 1 Kg',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '49.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    116 => 
    array (
      'nome' => 'SORBATO DE POTÁSIO - 1KG',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '56.80',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '1.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    117 => 
    array (
      'nome' => 'SUSPIRO',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '9.78',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    118 => 
    array (
      'nome' => 'TESOURA',
      'fornecedor' => 'ATACADÃO',
      'preco' => NULL,
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '1.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '0',
    ),
    119 => 
    array (
      'nome' => 'TIRA ACETATO ROLO 4 M x 10 Cm - BWB',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '7.88',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '4.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    120 => 
    array (
      'nome' => 'TIRA ACETATO ROLO 4 M x 15 Cm - BWB',
      'fornecedor' => 'CASA DO PANIFICADOR',
      'preco' => '10.35',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '1.000',
      'estoque_ideal' => '2.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    121 => 
    array (
      'nome' => 'TRIGO CISNE 5 Kg',
      'fornecedor' => 'FORT ATACADISTA',
      'preco' => '12.90',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '2.000',
      'estoque_ideal' => '5.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'KG',
      'conteudo' => '5.000',
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
    122 => 
    array (
      'nome' => 'UVA',
      'fornecedor' => 'WEBER HORTIFRUTI',
      'preco' => '12.00',
      'estoque_atual' => '0.000',
      'estoque_minimo' => '0.000',
      'estoque_ideal' => '0.000',
      'codigo_barras' => NULL,
      'codigo_compra' => NULL,
      'unidade_medida' => 'UN',
      'conteudo' => NULL,
      'imagem' => NULL,
      'controlar_estoque' => '1',
      'ativo' => '1',
    ),
  ),
  'fornecedores' => 
  array (
    0 => 
    array (
      'nome' => 'ATACADÃO',
      'ativo' => '1',
    ),
    1 => 
    array (
      'nome' => 'BR EMBALAGENS',
      'ativo' => '1',
    ),
    2 => 
    array (
      'nome' => 'CASA DO PANIFICADOR',
      'ativo' => '1',
    ),
    3 => 
    array (
      'nome' => 'CITBOX EMBALAGENS',
      'ativo' => '1',
    ),
    4 => 
    array (
      'nome' => 'FORT ATACADISTA',
      'ativo' => '1',
    ),
    5 => 
    array (
      'nome' => 'MERCADÃO DA EMBALAGEM',
      'ativo' => '1',
    ),
    6 => 
    array (
      'nome' => 'MIMO CRIATTIVO',
      'ativo' => '1',
    ),
    7 => 
    array (
      'nome' => 'WEBER HORTIFRUTI',
      'ativo' => '1',
    ),
  ),
  'gerado_em' => '2026-07-27T23:46:40+02:00',
);
